In [1]:
import tensorflow as tf
import tensorflow.keras.backend as K

1. expert_kernels (input_features * hidden_units * num_experts = 4 * 2 * 3)  
#input_features = 4  
#hidden_units = 2  
#num_experts = 3  

In [2]:
export_kernels = tf.constant([
    [[1., 1., 1.], [2., 2., 1.]],
    [[0.1, 0.5, 1.], [0.4, 0.1, 1.]],
    [[1., 1., 1.], [2., 2., 1.]],
    [[0., 1., 6.], [0., 2., 0.]]
    ], dtype=tf.float64
)

2. gate_kernels (input_features * num_experts * num_tasks = 4 * 3 * 2)

In [3]:
gate_kernels = [tf.constant([[0.1, 0.5, 1.], [0.4, 0.1, 1.], [1., 1., 1.], [2., 2., 1.]], dtype=tf.float64),
                tf.constant([[1., 2., 1.], [4., 0.2, 1.5], [2., 1., 0.], [5., 2., 1.]], dtype=tf.float64)]

#3. input samples (samples * input_features = 2 * 4)
#input_features = 4

In [4]:
inputs = tf.constant([[1., 2., 1., 0.], [4., 0.2, 1., 1.]], dtype=tf.float64)

4. expert_outputs = input * expert_kernels (samples * hidden_units * num_experts = 2 * 2 * 3)  
f_{i}(x) = activation(W_{i} * x + b)  
samples = 2, hidden_units = 2, num_experts = 3  

In [8]:
export_outputs = tf.tensordot(a=inputs, b=export_kernels, axes=1)

In [9]:
export_outputs

<tf.Tensor: shape=(2, 2, 3), dtype=float64, numpy=
array([[[ 2.2 ,  3.  ,  4.  ],
        [ 4.8 ,  4.2 ,  4.  ]],

       [[ 5.02,  6.1 , 11.2 ],
        [10.08, 12.02,  5.2 ]]])>

#5.gate_outputs = input * gate_kernels (num_tasks * samples * num_experts = 2 * 2 * 3)  
g^{k}(x) = activation(W_{g,k} * x + b)

In [10]:
gate_outputs = []
for index, gate_kernel in enumerate(gate_kernels):
    gate_output = K.dot(x=inputs, y=gate_kernel)
    gate_outputs.append(gate_output)

In [11]:
gate_outputs

[<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[1.9 , 1.7 , 4.  ],
        [3.48, 5.02, 6.2 ]])>, <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[11.  ,  3.4 ,  4.  ],
        [11.8 , 11.04,  5.3 ]])>]

In [12]:
gate_outputs = tf.nn.softmax(gate_outputs)